---
version: "3.2"
services:
  database:
    image: mcr.microsoft.com/mssql/rhel/server:2022-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: myLeet123Password!
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: {}