name: Deploy
on:
    push:
        branches:
            - main
            - beta
            - alpha

jobs:
    deploy_slug:
        runs-on: ubuntu-latest
        steps:
            - uses: rlespinasse/github-slug-action@v4
            - id: environment
              run: echo "var=${{ env.GITHUB_REF_SLUG_URL }}" >> $GITHUB_OUTPUT
            - id: tag
              run: echo "var=${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
        outputs:
            environment: ${{ steps.environment.outputs.var }}
            tag: ${{ steps.tag.outputs.var }}

    deploy:
        needs: deploy_slug
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            tag: ${{ needs.deploy_slug.outputs.tag }}
