name: Deploy
on:
    push:
        branches:
        - main
        - beta
        - alpha
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            deployments: write
        steps:
        -   uses: actions/checkout@v3
        -   uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 3.1.x
        -   uses: google-github-actions/auth@v1
            with:
                workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
                service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
        -   uses: pulumi/actions@v4
        -   run: ./deploy.sh