name: Unit test
on:
    pull_request:

jobs:
    #########################################################
    # Unit tests
    #########################################################
    test_unit_dotnet:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: read
            checks: write
            pull-requests: write
            statuses: write
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-dotnet@v3
          with:
              dotnet-version: 7.0
        - run: dotnet build App.Backend.Test
        - run: |
            dotnet test \
                --no-build \
                --blame \
                --blame-hang-timeout 2m

    test_unit_success:
        runs-on: ubuntu-latest
        needs:
        - test_unit_dotnet
        if: ${{ always() }}
        steps:
        -   run: |
                [[
                    '${{ needs.test_unit_dotnet.result }}' == 'success'
                ]]