name: Code quality
on:
    pull_request:

jobs:
    #########################################################
    # Code quality tests
    #########################################################
    test_quality_dotnet:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0
            - run: dotnet format --verify-no-changes

    # Terraform quality
    test_quality_terraform_tfsec:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
              with:
                  github_token: ${{ github.token }}

    test_quality_terraform_tflint:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: terraform-linters/setup-tflint@v4
              with:
                  tflint_version: v0.48
            - run: tflint --format compact

    test_quality_terraform_checkov:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: bridgecrewio/checkov-action@v12
              with:
                  directory: terraform/

    # Frontend
    test_quality_frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version-file: frontend/package.json
            - run: npm ci
              working-directory: frontend
            - run: npm run lint
              working-directory: frontend

    test_quality_success:
        runs-on: ubuntu-latest
        needs:
            - test_quality_dotnet
            - test_quality_frontend
            - test_quality_terraform_tfsec
            - test_quality_terraform_tflint
            - test_quality_terraform_checkov
        if: ${{ always() }}
        steps:
            - run: |
                  [[
                      '${{ needs.test_quality_dotnet.result }}' == 'success' &&
                      '${{ needs.test_quality_frontend.result }}' == 'success' &&
                      '${{ needs.test_quality_terraform_tfsec.result }}' == 'success'
                      '${{ needs.test_quality_terraform_tflint.result }}' == 'success'
                      '${{ needs.test_quality_terraform_checkov.result }}' == 'success'
                  ]]
