name: Unit test
on:
    pull_request:

jobs:
    #########################################################
    # Unit tests
    #########################################################
    test_unit_dotnet:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 7.0
        -   run: |
                dotnet test \
                    --verbosity diag \
                    --blame \
                    --blame-hang-timeout 5m
            env:
                DOTNET_ENVIRONMENT: Production
        - uses: actions/upload-artifact@v3
          if: failure()
          with:
              name: test_logs
              path: ./*/TestResults/**/*
              retention-days: 7
    
    test_unit_success:
        runs-on: ubuntu-latest
        needs:
        - test_unit_dotnet
        if: ${{ always() }}
        steps:
        -   run: |
                [[
                    '${{ needs.test_unit_dotnet.result }}' == 'success'
                ]]