name: Integration tests
on:
    pull_request:

jobs:
    deploy_slug:
        runs-on: ubuntu-latest
        steps:
            - uses: rlespinasse/github-slug-action@v4
            - id: environment
              run: echo "var=${{ env.GITHUB_REF_SLUG_URL }}" >> $GITHUB_OUTPUT
            - id: tag
              run: echo "var=${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
        outputs:
            environment: ${{ steps.environment.outputs.var }}
            tag: ${{ steps.tag.outputs.var }}

    deploy:
        needs: deploy_slug
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        permissions:
            contents: read
            id-token: write
            pages: write
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            version: ${{ needs.deploy_slug.outputs.tag }}

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        needs: deploy
        steps:
            - run: echo "::warning file=.github/workflows/test_integration.yml,::No integration tests implemented"

    destroy_backend:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        needs:
            - deploy_slug
            - deploy
            - test
        permissions:
            contents: read
        if: ${{ always() && needs.deploy.result != 'skipped' }}
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1
              with:
                  creds: '{"clientId":"${{ vars.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ vars.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ vars.ARM_TENANT_ID }}"}'
            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: '~1.6.3'
            - run: ./deploy.sh destroy -auto-approve
              env:
                  APP_VERSION: '${{ needs.deploy_slug.outputs.tag }}'
                  APP_ENVIRONMENT: '${{ needs.deploy_slug.outputs.environment }}'
                  APP_FRONTEND_URL: 'https:///blaat.com'
                  ARM_LOCATION: '${{ vars.ARM_LOCATION }}'
                  ARM_CLIENT_ID: '${{ vars.ARM_CLIENT_ID }}'
                  ARM_CLIENT_SECRET: '${{ secrets.ARM_CLIENT_SECRET }}'
                  ARM_SUBSCRIPTION_ID: '${{ vars.ARM_SUBSCRIPTION_ID }}'
                  ARM_TENANT_ID: '${{ vars.ARM_TENANT_ID }}'
                  AUTH0_DOMAIN: '${{ vars.AUTH0_DOMAIN }}'
                  AUTH0_CLIENT_ID: '${{ vars.AUTH0_CLIENT_ID }}'
                  AUTH0_CLIENT_SECRET: '${{ secrets.AUTH0_CLIENT_SECRET }}'
                  NORDIGEN_SECRET_ID: '${{ vars.NORDIGEN_SECRET_ID }}'
                  NORDIGEN_SECRET_KEY: '${{ secrets.NORDIGEN_SECRET_KEY }}'

    destroy_frontend:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        needs:
            - deploy_slug
            - deploy
            - test
        permissions:
            pages: write
            id-token: write
        if: ${{ always() && needs.deploy.result != 'skipped' }}
        environment:
            name: ${{ needs.deploy_slug.outputs.environment }}
        steps:
            - run: echo "::warning file=.github/workflows/test_integration.yml,::Destroy frontend not implemented"
