name: Test
on:
    pull_request:

jobs:
    #########################################################
    # Code quality tests
    #########################################################
    test_quality_dotnet:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0
            - run: dotnet format --verify-no-changes

    # Terraform quality
    test_quality_terraform:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: terraform-linters/setup-tflint@v4
            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "~1.6.3"
            - run: terraform fmt -check
              working-directory: terraform
            - run: tflint --format compact
              working-directory: terraform

    # Frontend
    test_quality_frontend:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false
                  package_json_file: frontend/package.json
            - uses: actions/setup-node@v4
              with:
                  node-version-file: frontend/package.json
                  cache: "pnpm"
                  cache-dependency-path: frontend/pnpm-lock.yaml
            - run: ./build.sh frontend
            - run: npm run lint
              working-directory: frontend
            - run: npm run build
              working-directory: frontend

    #########################################################
    # Unit tests
    #########################################################
    test_unit_dotnet:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: read
        strategy:
            matrix:
                project:
                    - App.Backend.Test
                    - App.Lib.InstitutionConnection.Test
                    - App.Lib.ServiceBus.Test
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0
            - run: dotnet build ${{ matrix.project }}
            - run: |
                  dotnet test ${{ matrix.project }} \
                      --no-build \
                      --blame \
                      --blame-hang-timeout 2m \
                      --logger "console;verbosity=normal"

    #########################################################
    # PR check
    #########################################################
    test_success:
        runs-on: ubuntu-latest
        needs:
            - test_unit_dotnet
            - test_quality_dotnet
            - test_quality_frontend
            - test_quality_terraform
        if: ${{ always() }}
        steps:
            - run: |
                  [[
                      '${{ needs.test_unit_dotnet.result }}' == 'success' &&
                      '${{ needs.test_quality_dotnet.result }}' == 'success' &&
                      '${{ needs.test_quality_frontend.result }}' == 'success' &&
                      '${{ needs.test_quality_terraform.result }}' == 'success'
                  ]]
