name: Integration tests
on:
    pull_request:

jobs:
    deploy_slug:
        runs-on: ubuntu-latest
        steps:
            - uses: rlespinasse/github-slug-action@v4
            - id: environment
              run: echo "var=${{ env.GITHUB_REF_SLUG_URL }}" >> $GITHUB_OUTPUT
            - id: tag
              run: echo "var=${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
        outputs:
            environment: ${{ steps.environment.outputs.var }}
            tag: ${{ steps.tag.outputs.var }}

    deploy:
        needs: deploy_slug
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        permissions:
            contents: read
            id-token: write
            pages: write
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            version: ${{ needs.deploy_slug.outputs.tag }}

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        needs: deploy
        steps:
            - run: echo "::warning file=.github/workflows/test_integration.yml,::No integration tests implemented"
