name: Integration tests
on:
    pull_request:

jobs:
    deploy_slug:
        runs-on: ubuntu-latest
        steps:
            - uses: rlespinasse/github-slug-action@v4
            - id: environment
              run: echo "var=${{ env.GITHUB_REF_SLUG_URL }}" >> $GITHUB_OUTPUT
            - id: tag
              run: echo "var=${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
        outputs:
            environment: ${{ steps.environment.outputs.var }}
            tag: ${{ steps.tag.outputs.var }}

    deploy:
        needs: deploy_slug
        if: ${{ needs.deploy_slug.outputs.environment != 'main' && needs.deploy_slug.outputs.environment != 'test' }}
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        permissions:
            contents: read
            deployments: write
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            version: ${{ needs.deploy_slug.outputs.tag }}

    test:
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright/dotnet:v1.39.0-jammy

        timeout-minutes: 30
        needs:
            - deploy
            - deploy_slug
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0
            - run: dotnet build App.IntegrationTest
            - run: |
                  echo "${APP_SETTINGS_JSON_ENCRYPTED}" | base64 -d | openssl enc -pbkdf2 -a -d -salt -pass pass:"${GH_ENCRYPT_KEY}" > App.IntegrationTest/appsettings.local.json
                  dotnet test App.IntegrationTest \
                      --no-build \
                      --blame \
                      --blame-hang-timeout 2m \
                      --logger GitHubActions
              env:
                  APP_SETTINGS_JSON_ENCRYPTED: ${{ needs.deploy.outputs.app_settings_json }}
                  GH_ENCRYPT_KEY: ${{ secrets.GH_ENCRYPT_KEY }}
            - uses: actions/upload-artifact@v2
              #if: failure()
              with:
                  name: test-traces
                  path: .test-traces/*.webm
