name: Unit test
on:
    pull_request:

jobs:
    #########################################################
    # Unit tests
    #########################################################
    test_unit_dotnet:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 7.0
        -   run: |
                echo "title=Test Run for PR #${{github.event.number}} Run #${{github.run_number}}" >> $GITHUB_ENV
                echo "file_name=TestReport.${{ matrix.project }}.${{github.sha}}.md" >> $GITHUB_ENV  
        -   run: dotnet test --verbosity detailed
            env:
                DOTNET_ENVIRONMENT: Production
    
    test_unit_success:
        runs-on: ubuntu-latest
        needs:
        - test_unit_dotnet
        if: ${{ always() }}
        steps:
        -   run: |
                [[
                    '${{ needs.test_unit_dotnet.result }}' == 'success'
                ]]