name: Code quality
on:
    pull_request:

jobs:
    #########################################################
    # Code quality tests
    #########################################################
    test_quality_dotnet:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0
            - run: dotnet format --verify-no-changes

    # Terraform quality
    test_quality_terraform:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: terraform-linters/setup-tflint@v4
            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "~1.6.3"
            - run: terraform fmt -check
              working-directory: terraform
            - run: tflint --format compact
              working-directory: terraform

    # Frontend
    test_quality_frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false
                  package_json_file: frontend/package.json
            - uses: actions/setup-node@v4
              with:
                  node-version-file: frontend/package.json
                  cache: "pnpm"
                  cache-dependency-path: frontend/pnpm-lock.yaml
            - run: ./build.sh frontend
            - run: pnpm run lint
              working-directory: frontend
            - run: pnpm run check
              working-directory: frontend

    test_quality_success:
        runs-on: ubuntu-latest
        needs:
            - test_quality_dotnet
            - test_quality_frontend
            - test_quality_terraform
        if: ${{ always() }}
        steps:
            - run: |
                  [[
                      '${{ needs.test_quality_dotnet.result }}' == 'success' &&
                      '${{ needs.test_quality_frontend.result }}' == 'success' &&
                      '${{ needs.test_quality_terraform.result }}' == 'success'
                  ]]
